[package]
name = "pdns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap ="1.1.0"
byteorder = "1"
chrono = "0.4.31"
strum = "0.17.1"
strum_macros = "0.17.1"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
phf = { version = "0.11", features = ["macros"] }
hex="0.4"
base64="0.21"
