dig +short domain +dnssec $1
dig +short 01giraffe.nl +dnssec $1
dig +short 10gen.cc +dnssec $1
dig +short 1191670140.rsc.cdn77.org +dnssec $1
dig +short 1198358605.rsc.cdn77.org +dnssec $1
dig +short 1220507597.rsc.cdn77.org +dnssec $1
dig +short 1278313086.rsc.cdn77.org +dnssec $1
dig +short 1280824805.rsc.cdn77.org +dnssec $1
dig +short 130.in-addr.arpa +dnssec $1
dig +short 1337x.to +dnssec $1
dig +short 1377x.to +dnssec $1
dig +short 1392738530.rsc.cdn77.org +dnssec $1
dig +short 140vf2viklmeenoms8lebgurei8vmovp.nl +dnssec $1
dig +short 1480222913.rsc.cdn77.org +dnssec $1
dig +short 149.in-addr.arpa +dnssec $1
dig +short 151.in-addr.arpa +dnssec $1
dig +short 1513871619.rsc.cdn77.org +dnssec $1
dig +short 1583888300.rsc.cdn77.org +dnssec $1
dig +short 1630983047.rsc.cdn77.org +dnssec $1
dig +short 166.in-addr.arpa +dnssec $1
dig +short 1671639327.rsc.cdn77.org +dnssec $1
dig +short 1751390105.rsc.cdn77.org +dnssec $1
dig +short 185.in-addr.arpa +dnssec $1
dig +short 192.in-addr.arpa +dnssec $1
dig +short 195.in-addr.arpa +dnssec $1
dig +short 2.ip6.arpa +dnssec $1
dig +short 2bii.nl +dnssec $1
dig +short 31q6habspul9notdp67v0t80ibdc56q4.nl +dnssec $1
dig +short 34.in-addr.arpa +dnssec $1
dig +short 3RL2Q58205687C8I9KC9MV46DGHCNS45.com +dnssec $1
dig +short 50487.edgekey.net +dnssec $1
dig +short 52.in-addr.arpa +dnssec $1
dig +short 555-timer-circuits.com +dnssec $1
dig +short 76.in-addr.arpa +dnssec $1
dig +short 77.in-addr.arpa +dnssec $1
dig +short 8.in-addr.arpa +dnssec $1
dig +short 81.in-addr.arpa +dnssec $1
dig +short a.akamaiedge.net +dnssec $1
dig +short a51.be +dnssec $1
dig +short aardsoft.fi +dnssec $1
dig +short ably.io +dnssec $1
dig +short acm.org +dnssec $1
dig +short ad.nl +dnssec $1
dig +short adobedtm.com +dnssec $1
dig +short adtidy.org +dnssec $1
dig +short adultdvdempire.com +dnssec $1
dig +short adultempire.com +dnssec $1
dig +short advanced-web-analytics.com +dnssec $1
dig +short aiden.cx +dnssec $1
dig +short ajax.googleapis.com +dnssec $1
dig +short ajay.app +dnssec $1
dig +short algolia.net +dnssec $1
dig +short algolianet.com +dnssec $1
dig +short allesineenssl.nl +dnssec $1
dig +short allestoringen.nl +dnssec $1
dig +short alltrails.com +dnssec $1
dig +short alphenaar.com +dnssec $1
dig +short altitudereservation.com +dnssec $1
dig +short alwyzon.net +dnssec $1
dig +short amazon.com +dnssec $1
dig +short amazon.map.fastly.net +dnssec $1
dig +short amazonaws.com +dnssec $1
dig +short amplience.net +dnssec $1
dig +short ampproject.org +dnssec $1
dig +short ams3.cdn.digitaloceanspaces.com +dnssec $1
dig +short anilos.com +dnssec $1
dig +short apexlink.to +dnssec $1
dig +short apple-mapkit.com +dnssec $1
dig +short apple.com +dnssec $1
dig +short arcpublishing.com +dnssec $1
dig +short asciinema.org +dnssec $1
dig +short at5.nl +dnssec $1
dig +short atl-paas.net +dnssec $1
dig +short atlassian.com +dnssec $1
dig +short autosecuredns.com +dnssec $1
dig +short avatars.githubusercontent.com +dnssec $1
dig +short aviationweather.gov +dnssec $1
dig +short ax4z.com +dnssec $1
dig +short ayepv6.com +dnssec $1
dig +short azure.com +dnssec $1
dig +short azurefd-t-fb-prod.trafficmanager.net +dnssec $1
dig +short b-cdn.net +dnssec $1
dig +short b.akamaiedge.net +dnssec $1
dig +short b01.azurefd.net +dnssec $1
dig +short bablic.com +dnssec $1
dig +short bazaarvoice.com +dnssec $1
dig +short bbc.co.uk +dnssec $1
dig +short bbc.com +dnssec $1
dig +short bbc.map.fastly.net +dnssec $1
dig +short bbci.co.uk +dnssec $1
dig +short bbcverticals.com +dnssec $1
dig +short bcbits.com +dnssec $1
dig +short bedbible.com +dnssec $1
dig +short beer.nl +dnssec $1
dig +short belnet.be +dnssec $1
dig +short belwue.net +dnssec $1
dig +short bier.nl +dnssec $1
dig +short billmill.org +dnssec $1
dig +short bittor.pw +dnssec $1
dig +short bizarro.com +dnssec $1
dig +short bjc908l1loujqoqo3cnben061ep48s17.nl +dnssec $1
dig +short blabbermouth.net +dnssec $1
dig +short boekbeschrijvingen.nl +dnssec $1
dig +short bol.com +dnssec $1
dig +short bonnier.cloud +dnssec $1
dig +short bonnierpublications.qualifioapp.com +dnssec $1
dig +short bootstrapcdn.com +dnssec $1
dig +short brein.nl +dnssec $1
dig +short buienradar.nl +dnssec $1
dig +short bunny.net +dnssec $1
dig +short button-bashers.nl +dnssec $1
dig +short bvisness.me +dnssec $1
dig +short bynder.com +dnssec $1
dig +short ca-v1.edgekey.net +dnssec $1
dig +short ca.edgekey.net +dnssec $1
dig +short cachefly.net +dnssec $1
dig +short cadmoremedia.com +dnssec $1
dig +short camo.githubusercontent.com +dnssec $1
dig +short canvasjs.com +dnssec $1
dig +short careerhub.com.au +dnssec $1
dig +short cbc.ca +dnssec $1
dig +short cbgames.s3.amazonaws.com +dnssec $1
dig +short ccv.eu +dnssec $1
dig +short ccvlabinfra.net +dnssec $1
dig +short cdn77.org +dnssec $1
dig +short cdne-shared-independer-static-prod.azureedge.net +dnssec $1
dig +short cdninstagram.com +dnssec $1
dig +short cedexis.net +dnssec $1
dig +short chaturbate.com +dnssec $1
dig +short chimpstatic.com +dnssec $1
dig +short chrisklomp.nl +dnssec $1
dig +short cidercounty.org.uk +dnssec $1
dig +short CK0POJMG874LJREF7EFN8430QVIT8BSM.com +dnssec $1
dig +short climbfinder.com +dnssec $1
dig +short cloudflare-dns.com +dnssec $1
dig +short cloudflare.com +dnssec $1
dig +short cloudflare.net +dnssec $1
dig +short cloudfront.com +dnssec $1
dig +short cloudfront.nl +dnssec $1
dig +short cloudimg.io +dnssec $1
dig +short cloudinary.com +dnssec $1
dig +short cloudns.net +dnssec $1
dig +short clubnzb.com +dnssec $1
dig +short cmax.ai +dnssec $1
dig +short cmdistro.com +dnssec $1
dig +short cmpl.azurewebsites.net +dnssec $1
dig +short codewars.com +dnssec $1
dig +short coloradointerlink.net +dnssec $1
dig +short com-v1.edgekey.net +dnssec $1
dig +short com.akadns.net +dnssec $1
dig +short com.akamaized.net +dnssec $1
dig +short com.cdn.cloudflare.net +dnssec $1
dig +short com.edgekey.net +dnssec $1
dig +short com.edgesuite.net +dnssec $1
dig +short comjagat.org +dnssec $1
dig +short config-inmobi-comtm.trafficmanager.net +dnssec $1
dig +short config-security.com +dnssec $1
dig +short config-server-eastus.trafficmanager.net +dnssec $1
dig +short content-autofill.googleapis.com +dnssec $1
dig +short contentful.com +dnssec $1
dig +short contentful.map.fastly.net +dnssec $1
dig +short contentstack.com +dnssec $1
dig +short contentstack.eu +dnssec $1
dig +short crates.io +dnssec $1
dig +short creator-spring.com +dnssec $1
dig +short cronon.de +dnssec $1
dig +short cronon.net +dnssec $1
dig +short csp.withgoogle.com +dnssec $1
dig +short ctfassets.net +dnssec $1
dig +short curbengh.github.io +dnssec $1
dig +short cvut.cz +dnssec $1
dig +short cxcomlive-webconvwa-weu.azurewebsites.net +dnssec $1
dig +short cyberwar.nl +dnssec $1
dig +short cyclingnews.com +dnssec $1
dig +short cyclingup.eu +dnssec $1
dig +short cyclinguptodate.com +dnssec $1
dig +short d11owpr6k4xtw5.cloudfront.net +dnssec $1
dig +short d1514ffbkialrc.cloudfront.net +dnssec $1
dig +short d1639lhkj5l89m.cloudfront.net +dnssec $1
dig +short d16zogpfyuwazr.cloudfront.net +dnssec $1
dig +short d185jh8djxl1sd.cloudfront.net +dnssec $1
dig +short d1aj75xh157otc.cloudfront.net +dnssec $1
dig +short d1fy50apkg1gx3.cloudfront.net +dnssec $1
dig +short d1gyz2dzs4t2p.cloudfront.net +dnssec $1
dig +short d1k7j1o9k2qyn1.cloudfront.net +dnssec $1
dig +short d1no706kdqz6t5.cloudfront.net +dnssec $1
dig +short d1o1dgn6uid35j.cloudfront.net +dnssec $1
dig +short d1t4ysgk276i17.cloudfront.net +dnssec $1
dig +short d1tcqh4bio8cty.cloudfront.net +dnssec $1
dig +short d1wcj4lc73o073.cloudfront.net +dnssec $1
dig +short d1yx7tdtmlx1ll.cloudfront.net +dnssec $1
dig +short d22ohr3ltkx6p.cloudfront.net +dnssec $1
dig +short d231vab146qzfb.cloudfront.net +dnssec $1
dig +short d26p99y3aj88fv.cloudfront.net +dnssec $1
dig +short d27scpai1jcyi9.cloudfront.net +dnssec $1
dig +short d285xo09kboqfo.cloudfront.net +dnssec $1
dig +short d2amxkt91ehiaf.cloudfront.net +dnssec $1
dig +short d2bebbf35ge2kr.cloudfront.net +dnssec $1
dig +short d2bytcopxu066p.cloudfront.net +dnssec $1
dig +short d2h6h75ulw8xr1.cloudfront.net +dnssec $1
dig +short d2jj6g4vsh8eh.cloudfront.net +dnssec $1
dig +short d2snzsztnvt919.cloudfront.net +dnssec $1
dig +short d2tzf0x91zo2h0.cloudfront.net +dnssec $1
dig +short d2v1zyclkbgero.cloudfront.net +dnssec $1
dig +short d2yksgaewnzzju.cloudfront.net +dnssec $1
dig +short d2z62su0aujguh.cloudfront.net +dnssec $1
dig +short d33a6lvgbd0fej.cloudfront.net +dnssec $1
dig +short d34azmi6bxg5fz.cloudfront.net +dnssec $1
dig +short d36kp9bkpbtn8z.cloudfront.net +dnssec $1
dig +short d3ah34wvbudrdd.cloudfront.net +dnssec $1
dig +short d3c4xqugy2ik4x.cloudfront.net +dnssec $1
dig +short d3du2k8g1u832i.cloudfront.net +dnssec $1
dig +short d3etkmmqcp13u4.cloudfront.net +dnssec $1
dig +short d3j7xsc0vda5xv.cloudfront.net +dnssec $1
dig +short d3jnur03fhemwu.cloudfront.net +dnssec $1
dig +short d3kdv2x2np28ys.cloudfront.net +dnssec $1
dig +short d3oiud1b8fohdw.cloudfront.net +dnssec $1
dig +short d3orhvfyxudxxq.cloudfront.net +dnssec $1
dig +short d3rgqpi5jj4aqa.cloudfront.net +dnssec $1
dig +short d3rwfxsf8lhub7.cloudfront.net +dnssec $1
dig +short d3smn1td4j2fg9.cloudfront.net +dnssec $1
dig +short d3vkowzfo3k1i1.cloudfront.net +dnssec $1
dig +short d6gjlglgq0c6f.cloudfront.net +dnssec $1
dig +short d83eunklitikj.cloudfront.net +dnssec $1
dig +short d87r0mmlmv594.cloudfront.net +dnssec $1
dig +short dan.com +dnssec $1
dig +short dataot.com +dnssec $1
dig +short datatables.net +dnssec $1
dig +short daywrzyvz0ar2.cloudfront.net +dnssec $1
dig +short db187550c7dkf.cloudfront.net +dnssec $1
dig +short dch1lry4ejfy9.cloudfront.net +dnssec $1
dig +short de2hoveniers.nl +dnssec $1
dig +short de4ertp2vqlc5.cloudfront.net +dnssec $1
dig +short desync.com +dnssec $1
dig +short dev.to +dnssec $1
dig +short dexeqbeb7giwr.cloudfront.net +dnssec $1
dig +short dhl.com +dnssec $1
dig +short dhlecommerce.nl +dnssec $1
dig +short dhlparcel.nl +dnssec $1
dig +short dictionary.com +dnssec $1
dig +short dictionary.map.fastly.net +dnssec $1
dig +short die.net +dnssec $1
dig +short digg.com +dnssec $1
dig +short digi.ninja +dnssec $1
dig +short digineo.de +dnssec $1
dig +short digitaaldagblad.nl +dnssec $1
dig +short dijkmat.nl +dnssec $1
dig +short discogs.com +dnssec $1
dig +short discourse-cdn.com +dnssec $1
dig +short disqus.com +dnssec $1
dig +short disquscdn.com +dnssec $1
dig +short dmdsdp.com +dnssec $1
dig +short dns-oarc.net +dnssec $1
dig +short dns.google +dnssec $1
dig +short dns.nl +dnssec $1
dig +short dnschecker.org +dnssec $1
dig +short dnscookie.com +dnssec $1
dig +short dnspython.readthedocs.io +dnssec $1
dig +short dnssec.nl +dnssec $1
dig +short docs.rs +dnssec $1
dig +short document360.io +dnssec $1
dig +short dogado.de +dnssec $1
dig +short dohp5p3sovzaz.cloudfront.net +dnssec $1
dig +short domains.nl +dnssec $1
dig +short domaintools.com +dnssec $1
dig +short doomcycle.com +dnssec $1
dig +short doomed-nation.com +dnssec $1
dig +short doppiocdn.com +dnssec $1
dig +short dotsrc.org +dnssec $1
dig +short downdetector.com +dnssec $1
dig +short downdetectorapi.com +dnssec $1
dig +short dpgm-pg-global.edgekey.net +dnssec $1
dig +short dpgmedia-net-wc-std.edgesuite.net +dnssec $1
dig +short dpgmedia-net-wc.edgekey.net +dnssec $1
dig +short dpgmedia.net +dnssec $1
dig +short dpp-ad-wc.edgekey.net +dnssec $1
dig +short dpp-nunl-wc.edgekey.net +dnssec $1
dig +short dqpnq362acqdi.cloudfront.net +dnssec $1
dig +short drm0dv0ymy5qa.cloudfront.net +dnssec $1
dig +short drnizx3otcofi.cloudfront.net +dnssec $1
dig +short dropbox-dns.com +dnssec $1
dig +short dropboxusercontent.com +dnssec $1
dig +short drunkenslug.com +dnssec $1
dig +short dsafe840ogevj.cloudfront.net +dnssec $1
dig +short dsca.akamaiedge.net +dnssec $1
dig +short dscb.akamai.net +dnssec $1
dig +short dscb.akamaiedge.net +dnssec $1
dig +short dscd.akamai.net +dnssec $1
dig +short dscd.akamaiedge.net +dnssec $1
dig +short dscf.akamaiedge.net +dnssec $1
dig +short dscg.akamaiedge.net +dnssec $1
dig +short dscg1.akamai.net +dnssec $1
dig +short dscg2.akamai.net +dnssec $1
dig +short dsci.akamaiedge.net +dnssec $1
dig +short dscj.akamaiedge.net +dnssec $1
dig +short dscq.akamai.net +dnssec $1
dig +short dscr.akamai.net +dnssec $1
dig +short dscx.akamaiedge.net +dnssec $1
dig +short dualstack.awsglobalaccelerator.com +dnssec $1
dig +short duckduckgo.com +dnssec $1
dig +short duivel.nl +dnssec $1
dig +short dutchgonewild.nl +dnssec $1
dig +short dvxdiz880bm14.cloudfront.net +dnssec $1
dig +short dyli5b7r35fla.cloudfront.net +dnssec $1
dig +short dyx6rm4e8ehws.cloudfront.net +dnssec $1
dig +short e12.akamaiedge.net +dnssec $1
dig +short e43jlmfjm7b0ob359cku1oek7gqqrdgd.be +dnssec $1
dig +short e9.akamaiedge.net +dnssec $1
dig +short eaeu.com +dnssec $1
dig +short earthlife.net +dnssec $1
dig +short easylist.to +dnssec $1
dig +short ec.azureedge.net +dnssec $1
dig +short ecdns.net +dnssec $1
dig +short edgecastcdn.net +dnssec $1
dig +short edgecastdns.net +dnssec $1
dig +short edgetag.io +dnssec $1
dig +short edurev.in +dnssec $1
dig +short efukt.com +dnssec $1
dig +short egq1ck3nri3lc7sfvdo887egavsgd5ss.nl +dnssec $1
dig +short elb.us-east-1.amazonaws.com +dnssec $1
dig +short elfsight.com +dnssec $1
dig +short elite.uk +dnssec $1
dig +short elitechnology.com +dnssec $1
dig +short eng-leadership.com +dnssec $1
dig +short enphaseenergy.com +dnssec $1
dig +short epsiloncdn.net +dnssec $1
dig +short etrusted.com +dnssec $1
dig +short example.be +dnssec $1
dig +short example.com +dnssec $1
dig +short example.nl +dnssec $1
dig +short example.org +dnssec $1
dig +short example1.com +dnssec $1
dig +short excathedra.co +dnssec $1
dig +short extended-dns-errors.com +dnssec $1
dig +short facebook.com +dnssec $1
dig +short facebook.net +dnssec $1
dig +short fastly.net +dnssec $1
dig +short fastlydns.net +dnssec $1
dig +short fb-t-msedge.net +dnssec $1
dig +short fbcdn.net +dnssec $1
dig +short fbsbx.com +dnssec $1
dig +short fcrmedia.com +dnssec $1
dig +short fcrtech.cz +dnssec $1
dig +short feelingbuggy.com +dnssec $1
dig +short fietsersbond.nl +dnssec $1
dig +short firefox.com +dnssec $1
dig +short firefoxusercontent.com +dnssec $1
dig +short firewall.cx +dnssec $1
dig +short fleshlight.com +dnssec $1
dig +short fluidplayer.com +dnssec $1
dig +short fok.nl +dnssec $1
dig +short fokstatic.nl +dnssec $1
dig +short fokzine.net +dnssec $1
dig +short fontawesome.com +dnssec $1
dig +short fonts.googleapis.com +dnssec $1
dig +short foo.com +dnssec $1
dig +short foobar.com +dnssec $1
dig +short footballcritic.com +dnssec $1
dig +short force.com +dnssec $1
dig +short forter.com +dnssec $1
dig +short fratec.net +dnssec $1
dig +short freerangecloud.com +dnssec $1
dig +short fsdn.com +dnssec $1
dig +short future.net.uk +dnssec $1
dig +short futurecdn.net +dnssec $1
dig +short g.akamaiedge.net +dnssec $1
dig +short gamma.nl +dnssec $1
dig +short garmin.com +dnssec $1
dig +short garmincdn.com +dnssec $1
dig +short geenstijl.nl +dnssec $1
dig +short geoip-prod-a-app.azurewebsites.net +dnssec $1
dig +short geoip-prod-in.trafficmanager.net +dnssec $1
dig +short getbootstrap.com +dnssec $1
dig +short ggpht.com +dnssec $1
dig +short gigya-api.com +dnssec $1
dig +short gigya.com +dnssec $1
dig +short giphy.com +dnssec $1
dig +short giphy.map.fastly.net +dnssec $1
dig +short gitbook.com +dnssec $1
dig +short gitbook.io +dnssec $1
dig +short github.com +dnssec $1
dig +short githubassets.com +dnssec $1
dig +short gitlab.com +dnssec $1
dig +short gitlab.net +dnssec $1
dig +short glitchtip.com +dnssec $1
dig +short globalcdn.co +dnssec $1
dig +short globalredir.akadns.net +dnssec $1
dig +short gmail.com +dnssec $1
dig +short go-vip.net +dnssec $1
dig +short go2cloud.org +dnssec $1
dig +short goadserver.com +dnssec $1
dig +short gonewild.nl +dnssec $1
dig +short google.be +dnssec $1
dig +short google.co +dnssec $1
dig +short google.com +dnssec $1
dig +short google.de +dnssec $1
dig +short google.nl +dnssec $1
dig +short googlehosted.com +dnssec $1
dig +short googlemail.com +dnssec $1
dig +short googleusercontent.com +dnssec $1
dig +short googlevideo.com +dnssec $1
dig +short goudengids.nl +dnssec $1
dig +short gracenote.com +dnssec $1
dig +short gravatar.com +dnssec $1
dig +short green.nl +dnssec $1
dig +short groenebouwmaterialen.nl +dnssec $1
dig +short groenheldenportaal.nl +dnssec $1
dig +short gstatic.com +dnssec $1
dig +short gstech.nl +dnssec $1
dig +short gtld-servers.net +dnssec $1
dig +short guardian.map.fastly.net +dnssec $1
dig +short guim.co.uk +dnssec $1
dig +short gumlet.com +dnssec $1
dig +short gumlet.io +dnssec $1
dig +short gvt1.com +dnssec $1
dig +short gwdg.de +dnssec $1
dig +short haag-heg.nl +dnssec $1
dig +short hackertarget.com +dnssec $1
dig +short hacktricks.xyz +dnssec $1
dig +short hal.science +dnssec $1
dig +short harmonystore.co.uk +dnssec $1
dig +short hatrack.com +dnssec $1
dig +short heavy-r.com +dnssec $1
dig +short helmuga.cloud +dnssec $1
dig +short heroku.com +dnssec $1
dig +short herynore.com +dnssec $1
dig +short heuvelsfietsen.nl +dnssec $1
dig +short highwebmedia.com +dnssec $1
dig +short historianet.nl +dnssec $1
dig +short honeybadger.io +dnssec $1
dig +short hornbach.nl +dnssec $1
dig +short hosted-by-discourse.com +dnssec $1
dig +short hosting4ever.nl +dnssec $1
dig +short hostname.bind ch txt +dnssec $1
dig +short hovenier.website +dnssec $1
dig +short hoveniersbedrijfvanmarwijk.nl +dnssec $1
dig +short howlandbolton.com +dnssec $1
dig +short hro.nl +dnssec $1
dig +short hsappstatic.net +dnssec $1
dig +short hscoscdn10.net +dnssec $1
dig +short hscoscdn20.net +dnssec $1
dig +short hscoscdn40.net +dnssec $1
dig +short hsforms.com +dnssec $1
dig +short huawei.com +dnssec $1
dig +short hubspot.com +dnssec $1
dig +short hubspot.net +dnssec $1
dig +short hubspotusercontent-na1.net +dnssec $1
dig +short hupso.com +dnssec $1
dig +short hypernode.io +dnssec $1
dig +short iana-servers.net +dnssec $1
dig +short iana.org +dnssec $1
dig +short ibm.com +dnssec $1
dig +short ibm.net +dnssec $1
dig +short ibmcom-tls12.edgekey.net +dnssec $1
dig +short ibmcom.edgekey.net +dnssec $1
dig +short icanhaz.nl +dnssec $1
dig +short icann.org +dnssec $1
dig +short ics.org +dnssec $1
dig +short ideal.nl +dnssec $1
dig +short ieee.org +dnssec $1
dig +short ietf.org +dnssec $1
dig +short iframe.ly +dnssec $1
dig +short ikbenaanwezig.nl +dnssec $1
dig +short imageupload.io +dnssec $1
dig +short imdb.com +dnssec $1
dig +short imgix.map.fastly.net +dnssec $1
dig +short imgix.net +dnssec $1
dig +short imgur.com +dnssec $1
dig +short imgur.map.fastly.net +dnssec $1
dig +short impervadns.net +dnssec $1
dig +short incapdns.net +dnssec $1
dig +short independent.co.uk +dnssec $1
dig +short independer-static.nl +dnssec $1
dig +short independer.nl +dnssec $1
dig +short infoblox.com +dnssec $1
dig +short ing.nl +dnssec $1
dig +short ingenico.com +dnssec $1
dig +short inmobi.com +dnssec $1
dig +short instagram.com +dnssec $1
dig +short interactive-life-forms.myshopify.com +dnssec $1
dig +short interactives.dk +dnssec $1
dig +short intercom.io +dnssec $1
dig +short intercomcdn.com +dnssec $1
dig +short intercomcdn.eu +dnssec $1
dig +short ionite.net +dnssec $1
dig +short iphh.net +dnssec $1
dig +short ipify.org +dnssec $1
dig +short ipv4only.arpa +dnssec $1
dig +short isc.org +dnssec $1
dig +short isolatiemateriaal.nl +dnssec $1
dig +short istockphoto.com +dnssec $1
dig +short itemfix.com +dnssec $1
dig +short iusmentis.com +dnssec $1
dig +short jamieweb.net +dnssec $1
dig +short jeedoo.com +dnssec $1
dig +short jetbrains.ai +dnssec $1
dig +short jetbrains.com +dnssec $1
dig +short jnn-pa.googleapis.com +dnssec $1
dig +short jobboard.io +dnssec $1
dig +short joram.it +dnssec $1
dig +short jquery.com +dnssec $1
dig +short jsdelivr.map.fastly.net +dnssec $1
dig +short jsdelivr.net +dnssec $1
dig +short jvns.ca +dnssec $1
dig +short jwpcdn.com +dnssec $1
dig +short jwplatform.com +dnssec $1
dig +short jwplayer-dualstack.map.fastly.net +dnssec $1
dig +short jwplayer.com +dnssec $1
dig +short jwpsrv.com +dnssec $1
dig +short k-machine.com +dnssec $1
dig +short k36vo59bkum4osckkrd8tvibdgr0njbc.nl +dnssec $1
dig +short k8s-gs-5c0d8cda5c-1539961167.us-east-1.elb.amazonaws.com +dnssec $1
dig +short kaartenhuis.nl +dnssec $1
dig +short kali.org +dnssec $1
dig +short karneval.cz +dnssec $1
dig +short kc-usercontent.com +dnssec $1
dig +short kijkmagazine.nl +dnssec $1
dig +short kinde.com +dnssec $1
dig +short klantenvertellen.nl +dnssec $1
dig +short kmachine.nl +dnssec $1
dig +short knock.app +dnssec $1
dig +short kwalinux.nl +dnssec $1
dig +short kxcdn.com +dnssec $1
dig +short l-msedge.net +dnssec $1
dig +short large.nl +dnssec $1
dig +short launchdarkly.com +dnssec $1
dig +short lc-api.net +dnssec $1
dig +short leaseweb.net +dnssec $1
dig +short lencr.edgesuite.net +dnssec $1
dig +short lencr.org +dnssec $1
dig +short lgi.io +dnssec $1
dig +short li-publicationapi.azurewebsites.net +dnssec $1
dig +short licdn.com +dnssec $1
dig +short linearicons.com +dnssec $1
dig +short linkedin.com +dnssec $1
dig +short linkfire.com +dnssec $1
dig +short linux.cz +dnssec $1
dig +short linuxnijmegen.nl +dnssec $1
dig +short liquidtelecom.com +dnssec $1
dig +short liteserver.nl +dnssec $1
dig +short liu.se +dnssec $1
dig +short live-federated-id-alb-1756651342.eu-west-1.elb.amazonaws.com +dnssec $1
dig +short liz.nl +dnssec $1
dig +short lncontent.works +dnssec $1
dig +short loginradius.com +dnssec $1
dig +short loox.io +dnssec $1
dig +short lovehoney.com +dnssec $1
dig +short lovehoneyassets.com +dnssec $1
dig +short lovepanky.com +dnssec $1
dig +short lrcontent.com +dnssec $1
dig +short luchtdichtshop.nl +dnssec $1
dig +short lync.com +dnssec $1
dig +short m-w.com +dnssec $1
dig +short madeinbern.com +dnssec $1
dig +short magic-wormhole.readthedocs.io +dnssec $1
dig +short malware-filter.gitlab.io +dnssec $1
dig +short malware-filter.pages.dev +dnssec $1
dig +short man.poznan.pl +dnssec $1
dig +short mapbox.com +dnssec $1
dig +short mapotofu.org +dnssec $1
dig +short maps.googleapis.com +dnssec $1
dig +short marechaussee.nl +dnssec $1
dig +short marketingautomation.services +dnssec $1
dig +short media-amazon.com +dnssec $1
dig +short media-dpgmm.edgesuite.net +dnssec $1
dig +short media-imdb.com +dnssec $1
dig +short medium.com +dnssec $1
dig +short merriam-webster.com +dnssec $1
dig +short met.no +dnssec $1
dig +short metal-archives.com +dnssec $1
dig +short metalfan.nl +dnssec $1
dig +short microsoft.com +dnssec $1
dig +short microsoft.nl +dnssec $1
dig +short mislove.org +dnssec $1
dig +short mmcdn.com +dnssec $1
dig +short mmcdn.nl +dnssec $1
dig +short mnemonic.no +dnssec $1
dig +short mopinion.com +dnssec $1
dig +short moviemeter.nl +dnssec $1
dig +short moz.works +dnssec $1
dig +short mozaws.net +dnssec $1
dig +short mozgcp.net +dnssec $1
dig +short mozilla.com +dnssec $1
dig +short mozilla.net +dnssec $1
dig +short mozilla.org +dnssec $1
dig +short msecnd.net +dnssec $1
dig +short mu.se +dnssec $1
dig +short multimirror.io +dnssec $1
dig +short musement.com +dnssec $1
dig +short musictheory.net +dnssec $1
dig +short mvps.org +dnssec $1
dig +short mycity.travel +dnssec $1
dig +short mycols.app +dnssec $1
dig +short myspacecdn.com +dnssec $1
dig +short mysql.com +dnssec $1
dig +short myvaud.ch +dnssec $1
dig +short namesilo.com +dnssec $1
dig +short narkive.com +dnssec $1
dig +short narkive.net +dnssec $1
dig +short net.cdn.cloudflare.net +dnssec $1
dig +short net.edgekey.net +dnssec $1
dig +short net.edgesuite.net +dnssec $1
dig +short netflash.com.cy +dnssec $1
dig +short netlifyglobalcdn.com +dnssec $1
dig +short netmeister.org +dnssec $1
dig +short newsifier.nl +dnssec $1
dig +short newspark.ca +dnssec $1
dig +short nextday.media +dnssec $1
dig +short nextinsure.com +dnssec $1
dig +short nieuwnieuws.nl +dnssec $1
dig +short nitrocdn.com +dnssec $1
dig +short nitroscripts.com +dnssec $1
dig +short nl-v1.edgekey.net +dnssec $1
dig +short nl.akamaized.net +dnssec $1
dig +short nl.com +dnssec $1
dig +short nl.edgekey.net +dnssec $1
dig +short nl.edgesuite.net +dnssec $1
dig +short nlnetlabs.nl +dnssec $1
dig +short nluug.nl +dnssec $1
dig +short nordcdn.com +dnssec $1
dig +short nordvpn.com +dnssec $1
dig +short nordvpn.net +dnssec $1
dig +short nos.nl +dnssec $1
dig +short npmcdn.com +dnssec $1
dig +short npmjs.com +dnssec $1
dig +short npo.nl +dnssec $1
dig +short npocloud.nl +dnssec $1
dig +short nporadio.nl +dnssec $1
dig +short nporadio2.nl +dnssec $1
dig +short npox.nl +dnssec $1
dig +short nrc.nl +dnssec $1
dig +short nslookup.io +dnssec $1
dig +short nu.com +dnssec $1
dig +short nu.nl +dnssec $1
dig +short nubiles-porn.com +dnssec $1
dig +short nun.nl +dnssec $1
dig +short nvidia.com +dnssec $1
dig +short offroadbikers.eu +dnssec $1
dig +short ogads-pa.googleapis.com +dnssec $1
dig +short ogone.com +dnssec $1
dig +short OHEG5A2TO40VP3ANF9CGVSDNSJG2JQOH.com +dnssec $1
dig +short omroepwest.nl +dnssec $1
dig +short omtrdc.net +dnssec $1
dig +short onenet.nl +dnssec $1
dig +short onlinepianocoach.com +dnssec $1
dig +short open-xchange.com +dnssec $1
dig +short openhab.org +dnssec $1
dig +short openstreetmap.org +dnssec $1
dig +short opensuse.org +dnssec $1
dig +short ophan.co.uk +dnssec $1
dig +short opta.net +dnssec $1
dig +short optimizationguide-pa.googleapis.com +dnssec $1
dig +short oracle.com +dnssec $1
dig +short oscaralblas.nl +dnssec $1
dig +short parcelpro.nl +dnssec $1
dig +short parkos.nl +dnssec $1
dig +short patronaat.nl +dnssec $1
dig +short pdrpqgs0t19r8qul7c2h4bhnb7agh1b8.be +dnssec $1
dig +short pentest-tools.com +dnssec $1
dig +short perimeterx.map.fastly.net +dnssec $1
dig +short pexi.nl +dnssec $1
dig +short pezcyclingnews.com +dnssec $1
dig +short phicdn.net +dnssec $1
dig +short phishing-filter.pages.dev +dnssec $1
dig +short phncdn.com +dnssec $1
dig +short photobucket.com +dnssec $1
dig +short php.net +dnssec $1
dig +short physioinq.com.au +dnssec $1
dig +short pi-hole.net +dnssec $1
dig +short pijper.io +dnssec $1
dig +short pinimg.com +dnssec $1
dig +short pinterest.com +dnssec $1
dig +short pinterest.map.fastly.net +dnssec $1
dig +short piwik.pro +dnssec $1
dig +short pki.goog +dnssec $1
dig +short platformos.com +dnssec $1
dig +short platformrijksoverheid.nl +dnssec $1
dig +short plesk.com +dnssec $1
dig +short plumule.nl +dnssec $1
dig +short plyr.io +dnssec $1
dig +short popsci.com +dnssec $1
dig +short pornedup.com +dnssec $1
dig +short pornhub.com +dnssec $1
dig +short postimg.cc +dnssec $1
dig +short powerdns.com +dnssec $1
dig +short powr.io +dnssec $1
dig +short powrcdn.com +dnssec $1
dig +short premium-storefronts.s3.amazonaws.com +dnssec $1
dig +short princeton.edu +dnssec $1
dig +short printlane.com +dnssec $1
dig +short privacy-center.org +dnssec $1
dig +short privacy-mgmt.com +dnssec $1
dig +short procyclingstats.com +dnssec $1
dig +short prod-mw-plausiblelb-1445410871.us-east-1.elb.amazonaws.com +dnssec $1
dig +short programiz.com +dnssec $1
dig +short protechts.net +dnssec $1
dig +short psnc.pl +dnssec $1
dig +short psp-solutions.com +dnssec $1
dig +short public-dns.info +dnssec $1
dig +short publicsuffix.org +dnssec $1
dig +short px-cloud.net +dnssec $1
dig +short pypi.org +dnssec $1
dig +short python.map.fastly.net +dnssec $1
dig +short pythonhosted.org +dnssec $1
dig +short qualif.io +dnssec $1
dig +short qualifio.com +dnssec $1
dig +short quic.map.fastly.net +dnssec $1
dig +short quora.com +dnssec $1
dig +short quoracdn.net +dnssec $1
dig +short r3be2rr467hhiojmbu0qq7sfignm1kog.be +dnssec $1
dig +short radio-canada.ca +dnssec $1
dig +short ravanallc.com +dnssec $1
dig +short ravenjs.com +dnssec $1
dig +short raw.githubusercontent.com +dnssec $1
dig +short readspeaker.com +dnssec $1
dig +short readthedocs.org +dnssec $1
dig +short realtimesnetwork.com +dnssec $1
dig +short rebrand.ly +dnssec $1
dig +short recaptcha.net +dnssec $1
dig +short receptivity.io +dnssec $1
dig +short rechargecdn.com +dnssec $1
dig +short recombee.com +dnssec $1
dig +short recurly.com +dnssec $1
dig +short redd.it +dnssec $1
dig +short reddit.com +dnssec $1
dig +short reddit.map.fastly.net +dnssec $1
dig +short redditmedia.com +dnssec $1
dig +short redditspace.com +dnssec $1
dig +short redditstatic.com +dnssec $1
dig +short redgifs.com +dnssec $1
dig +short refined.site +dnssec $1
dig +short regiogroei.cloud +dnssec $1
dig +short relevant-digital.com +dnssec $1
dig +short researchgate.net +dnssec $1
dig +short retribution.nl +dnssec $1
dig +short reuters.com +dnssec $1
dig +short reutersmedia.net +dnssec $1
dig +short rfc-editor.org +dnssec $1
dig +short rijksoverheid.nl +dnssec $1
dig +short rijwind.com +dnssec $1
dig +short ripe.net +dnssec $1
dig +short rm.nl +dnssec $1
dig +short rncdn4.com +dnssec $1
dig +short rncdn7.com +dnssec $1
dig +short roedu.net +dnssec $1
dig +short ROOT-SERVERS.NET +dnssec $1
dig +short rotterdamthehagueairport.nl +dnssec $1
dig +short roularta.be +dnssec $1
dig +short rsa3dsauth.co.uk +dnssec $1
dig +short rsms.me +dnssec $1
dig +short rtl.nl +dnssec $1
dig +short ru.nl +dnssec $1
dig +short rust-lang.github.io +dnssec $1
dig +short rust-lang.org +dnssec $1
dig +short rwth-aachen.de +dnssec $1
dig +short ryazabti.com +dnssec $1
dig +short rzone.de +dnssec $1
dig +short s-bol.com +dnssec $1
dig +short s3-w.us-east-1.amazonaws.com +dnssec $1
dig +short s81c.com +dnssec $1
dig +short safebrowsing.googleapis.com +dnssec $1
dig +short salesforce.com +dnssec $1
dig +short salesianimestre.it +dnssec $1
dig +short satan.nl +dnssec $1
dig +short scalia.network +dnssec $1
dig +short scashwl.com +dnssec $1
dig +short schemastore.org +dnssec $1
dig +short schemastore2.azurewebsites.net +dnssec $1
dig +short schlundtech.de +dnssec $1
dig +short scripts.qualifioapp.com +dnssec $1
dig +short seamlessaccess.org +dnssec $1
dig +short seamly-app.com +dnssec $1
dig +short season-of-mist.com +dnssec $1
dig +short sectigo.com +dnssec $1
dig +short securesuite.co.uk +dnssec $1
dig +short security.nl +dnssec $1
dig +short serde.rs +dnssec $1
dig +short serverfault.com +dnssec $1
dig +short setlist.fm +dnssec $1
dig +short setlistfm.com +dnssec $1
dig +short sexbook.nl +dnssec $1
dig +short sexjobs.nl +dnssec $1
dig +short sexualalpha.com +dnssec $1
dig +short sftcdn.net +dnssec $1
dig +short shields.io +dnssec $1
dig +short shop.app +dnssec $1
dig +short shopify.com +dnssec $1
dig +short shopifycdn.com +dnssec $1
dig +short shops.myshopify.com +dnssec $1
dig +short shrsl.com +dnssec $1
dig +short shuttle.rs +dnssec $1
dig +short sickjunk.com +dnssec $1
dig +short sidn.com +dnssec $1
dig +short sidn.nl +dnssec $1
dig +short sidnlabs.nl +dnssec $1
dig +short sigmacdn.net +dnssec $1
dig +short signal.org +dnssec $1
dig +short siteground.biz +dnssec $1
dig +short sitesearch360.com +dnssec $1
dig +short sixxs.net +dnssec $1
dig +short slashdot.org +dnssec $1
dig +short slutroulette.com +dnssec $1
dig +short slutroulette.org +dnssec $1
dig +short snapcraft.io +dnssec $1
dig +short snapcraftcontent.com +dnssec $1
dig +short snigelweb.com +dnssec $1
dig +short softonic.nl +dnssec $1
dig +short someonewhocares.org +dnssec $1
dig +short spiceworks.com +dnssec $1
dig +short sportsbase.io +dnssec $1
dig +short sporza.be +dnssec $1
dig +short spotify.com +dnssec $1
dig +short spotify.map.fastly.net +dnssec $1
dig +short spri.ng +dnssec $1
dig +short squarespace-cdn.com +dnssec $1
dig +short squarespace.com +dnssec $1
dig +short squarespace.map.fastly.net +dnssec $1
dig +short sr.ht +dnssec $1
dig +short ssl-images-amazon.com +dnssec $1
dig +short sstatic.net +dnssec $1
dig +short stackexchange.com +dnssec $1
dig +short stackoverflow.com +dnssec $1
dig +short stager-prod.s3.eu-west-1.amazonaws.com +dnssec $1
dig +short stager.co +dnssec $1
dig +short star-azurefd-prod.trafficmanager.net +dnssec $1
dig +short statically.io +dnssec $1
dig +short statically.map.fastly.net +dnssec $1
dig +short staticflickr.com +dnssec $1
dig +short steffann.nl +dnssec $1
dig +short storage.googleapis.com +dnssec $1
dig +short strato.com +dnssec $1
dig +short strato.de +dnssec $1
dig +short strato.nl +dnssec $1
dig +short streetviewpixels-pa.googleapis.com +dnssec $1
dig +short stretching-exercises-guide.com +dnssec $1
dig +short stripe.com +dnssec $1
dig +short stripe.network +dnssec $1
dig +short stripecdn.map.fastly.net +dnssec $1
dig +short stripst.com +dnssec $1
dig +short strpst.com +dnssec $1
dig +short substack-custom-domains.com +dnssec $1
dig +short substackcdn.com +dnssec $1
dig +short sunnycars.com +dnssec $1
dig +short superuser.com +dnssec $1
dig +short svelte.dev +dnssec $1
dig +short swls.map.fastly.net +dnssec $1
dig +short t-msedge.net +dnssec $1
dig +short t.co +dnssec $1
dig +short takkenkamp.com +dnssec $1
dig +short tawk.to +dnssec $1
dig +short technolution.com +dnssec $1
dig +short technolution.eu +dnssec $1
dig +short technolution.nl +dnssec $1
dig +short teespring.com +dnssec $1
dig +short telesec.de +dnssec $1
dig +short teleweer.nl +dnssec $1
dig +short test-ipv6.cl +dnssec $1
dig +short test-ipv6.com +dnssec $1
dig +short test-ipv6.hu +dnssec $1
dig +short test-ipv6.nl +dnssec $1
dig +short test-ipv6.se +dnssec $1
dig +short testifier.nl +dnssec $1
dig +short the-independent.com +dnssec $1
dig +short theconversation.com +dnssec $1
dig +short theguardian.com +dnssec $1
dig +short themoviedb.org +dnssec $1
dig +short theoplayer.com +dnssec $1
dig +short thunderbird.net +dnssec $1
dig +short tjeb.nl +dnssec $1
dig +short tmdb.org +dnssec $1
dig +short tno.nl +dnssec $1
dig +short torrentsearch.com +dnssec $1
dig +short touretappe.nl +dnssec $1
dig +short tourtrackerdata.com +dnssec $1
dig +short transavia.com +dnssec $1
dig +short translate.googleapis.com +dnssec $1
dig +short trib.al +dnssec $1
dig +short trustarc.com +dnssec $1
dig +short truste.com +dnssec $1
dig +short trustpilot.com +dnssec $1
dig +short tspu.edu.ru +dnssec $1
dig +short tspu.ru +dnssec $1
dig +short tu-chemnitz.de +dnssec $1
dig +short tui.com +dnssec $1
dig +short tui.nl +dnssec $1
dig +short tuicontent.nl +dnssec $1
dig +short tumblr.com +dnssec $1
dig +short tunnelbroker.net +dnssec $1
dig +short tv.edgekey.net +dnssec $1
dig +short tweakers.net +dnssec $1
dig +short twimg.com +dnssec $1
dig +short twitframe.com +dnssec $1
dig +short twitter.com +dnssec $1
dig +short twitter.map.fastly.net +dnssec $1
dig +short typekit.net +dnssec $1
dig +short ublockorigin.github.io +dnssec $1
dig +short ublockorigin.pages.dev +dnssec $1
dig +short ucom.am +dnssec $1
dig +short uk.edgekey.net +dnssec $1
dig +short ultimate-guitar.com +dnssec $1
dig +short un.nl +dnssec $1
dig +short uni-erlangen.de +dnssec $1
dig +short unpkg.com +dnssec $1
dig +short upcbroadband.com +dnssec $1
dig +short update.googleapis.com +dnssec $1
dig +short us-central1-digitalproducts-gabbo.cloudfunctions.net +dnssec $1
dig +short us-central1-ipgeolocation-414906.cloudfunctions.net +dnssec $1
dig +short usenetbucket.com +dnssec $1
dig +short usenix.org +dnssec $1
dig +short usercentrics.eu +dnssec $1
dig +short usna.edu +dnssec $1
dig +short ustatik.com +dnssec $1
dig +short utwente.nl +dnssec $1
dig +short uwaterloo.ca +dnssec $1
dig +short v0cdn.net +dnssec $1
dig +short vanegmondtuinen.nl +dnssec $1
dig +short varnish.qualifioapp.com +dnssec $1
dig +short vectranet.pl +dnssec $1
dig +short vercel-dns.com +dnssec $1
dig +short version.bind ch txt +dnssec $1
dig +short viafoura.co +dnssec $1
dig +short viafoura.net +dnssec $1
dig +short vicrecords.com +dnssec $1
dig +short vimeo.com +dnssec $1
dig +short visualstudio.com +dnssec $1
dig +short voorburgsdagblad.nl +dnssec $1
dig +short voyeur-house.tv +dnssec $1
dig +short vrt.be +dnssec $1
dig +short vyncke.org +dnssec $1
dig +short w.org +dnssec $1
dig +short w3schools.com +dnssec $1
dig +short watersprings.org +dnssec $1
dig +short waws-prod-am2-083.westeurope.cloudapp.azure.com +dnssec $1
dig +short wcdnga.com +dnssec $1
dig +short webpkgcache.com +dnssec $1
dig +short webshopapp.com +dnssec $1
dig +short webwinkelkeur.nl +dnssec $1
dig +short weer.nl +dnssec $1
dig +short weeronline.nl +dnssec $1
dig +short weglot.com +dnssec $1
dig +short wendy.org +dnssec $1
dig +short wenzperl.nl +dnssec $1
dig +short whatsapp.com +dnssec $1
dig +short whatsapp.net +dnssec $1
dig +short wielerflits.be +dnssec $1
dig +short wielerflits.nl +dnssec $1
dig +short wielerrevue.nl +dnssec $1
dig +short wikimedia.org +dnssec $1
dig +short wikipedia.org +dnssec $1
dig +short wikiwand.com +dnssec $1
dig +short wiktionary.org +dnssec $1
dig +short windows.net +dnssec $1
dig +short wordpress.com +dnssec $1
dig +short worldline-solutions.com +dnssec $1
dig +short wp.com +dnssec $1
dig +short wp.wpenginepowered.com +dnssec $1
dig +short wpeproxy.com +dnssec $1
dig +short www.googleapis.com +dnssec $1
dig +short x.com +dnssec $1
dig +short xnxx-cdn.com +dnssec $1
dig +short xnxx.com +dnssec $1
dig +short xolphin.com +dnssec $1
dig +short xs4all.nl +dnssec $1
dig +short xvideos-cdn.com +dnssec $1
dig +short xvideos.com +dnssec $1
dig +short xxxcambabes.nl +dnssec $1
dig +short yandex.ru +dnssec $1
dig +short yotpo.com +dnssec $1
dig +short yourdomainprovider.net +dnssec $1
dig +short youtube-nocookie.com +dnssec $1
dig +short youtube.com +dnssec $1
dig +short yoyo.org +dnssec $1
dig +short yp.to +dnssec $1
dig +short ytimg.com +dnssec $1
dig +short z01.azurefd.net +dnssec $1
dig +short zi-scripts.com +dnssec $1
dig +short ziffstatic.com +dnssec $1
dig +short ziggo.nl +dnssec $1
dig +short ziggogo.tv +dnssec $1
dig +short zombie.nl +dnssec $1
dig +short zombies.nl +dnssec $1
dig +short zonetransfer.me +dnssec $1
dig +short zoorix.com +dnssec $1
dig +short zwaremetalen.com +dnssec $1
dig +short eddie4.nl +dnssec $1
dig miek.nl loc +dnssec +short $1
dig forfun.net loc +dnssec +short $1
