dig +short +nocomment  types.wb.sidnlabs.nl. SOA $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  a.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  a01.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  a02.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  aaaa.types.wb.sidnlabs.nl. AAAA $1
dig +short +nocomment  afsdb.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  afsdb01.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  afsdb02.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  cds.types.wb.sidnlabs.nl. CDS $1
dig +short +nocomment  cert.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  cert01.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  cname.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  cname01.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  cname02.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  csync.types.wb.sidnlabs.nl. CSYNC $1
dig +short +nocomment  dhcid.types.wb.sidnlabs.nl. DHCID $1
dig +short +nocomment  dname.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname01.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname02.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname03.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  eui48.types.wb.sidnlabs.nl. EUI48 $1
dig +short +nocomment  eui64.types.wb.sidnlabs.nl. EUI64 $1
dig +short +nocomment  gpos.types.wb.sidnlabs.nl. GPOS $1
dig +short +nocomment  hinfo.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  hinfo01.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  hinfo02.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  isdn.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn01.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn02.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn03.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn04.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  kx.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  kx01.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  kx02.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  l32.types.wb.sidnlabs.nl. L32 $1
dig +short +nocomment  l64.types.wb.sidnlabs.nl. L64 $1
dig +short +nocomment  loc.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  loc01.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  loc02.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  lp.types.wb.sidnlabs.nl. LP $1
dig +short +nocomment  mb.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  md.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  mf.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  mg.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  mg01.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  mg02.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  minfo.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  minfo01.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  mr.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mr01.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mr02.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mx.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  mx01.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  naptr.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  naptr01.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  naptr02.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  nid.types.wb.sidnlabs.nl. NID $1
dig +short +nocomment  ninfo.types.wb.sidnlabs.nl. NINFO $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  nsap.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  nsap01.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  ptr01.types.wb.sidnlabs.nl. PTR $1
dig +short +nocomment  px.types.wb.sidnlabs.nl. PX $1
dig +short +nocomment  rkey.types.wb.sidnlabs.nl. RKEY $1
dig +short +nocomment  rp.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rp01.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rp02.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rt.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  rt01.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  rt02.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  spf.types.wb.sidnlabs.nl. SPF $1
dig +short +nocomment  srv.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  srv01.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  srv02.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  talink.types.wb.sidnlabs.nl. TALINK $1
dig +short +nocomment  tlsa.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  tlsa2.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  txt.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt01.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt02.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt03.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt04.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt05.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt06.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt07.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt08.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt09.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt10.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt11.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt12.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type1.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  type104.types.wb.sidnlabs.nl. NID $1
dig +short +nocomment  type105.types.wb.sidnlabs.nl. L32 $1
dig +short +nocomment  type106.types.wb.sidnlabs.nl. L64 $1
dig +short +nocomment  type107.types.wb.sidnlabs.nl. LP $1
dig +short +nocomment  type108.types.wb.sidnlabs.nl. EUI48 $1
dig +short +nocomment  type109.types.wb.sidnlabs.nl. EUI64 $1
dig +short +nocomment  type11.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  type12.types.wb.sidnlabs.nl. PTR $1
dig +short +nocomment  type13.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  type14.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  type15.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  type16.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type17.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  type18.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  type19.types.wb.sidnlabs.nl. X25 $1
dig +short +nocomment  type20.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  type21.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  type22.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  type257.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  type26.types.wb.sidnlabs.nl. PX $1
dig +short +nocomment  type27.types.wb.sidnlabs.nl. GPOS $1
dig +short +nocomment  type28.types.wb.sidnlabs.nl. AAAA $1
dig +short +nocomment  type29.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  type3.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type33.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  type35.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  type36.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  type37.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  type39.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  type4.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type49.types.wb.sidnlabs.nl. DHCID $1
dig +short +nocomment  type5.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  type52.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  type56.types.wb.sidnlabs.nl. NINFO $1
dig +short +nocomment  type57.types.wb.sidnlabs.nl. RKEY $1
dig +short +nocomment  type58.types.wb.sidnlabs.nl. TALINK $1
dig +short +nocomment  type59.types.wb.sidnlabs.nl. CDS $1
dig +short +nocomment  type7.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type8.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  type9.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  type99.types.wb.sidnlabs.nl. SPF $1
dig +short +nocomment  wks.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  wks01.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  wks02.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  www.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  x25.types.wb.sidnlabs.nl. X25 $1
dig +short +nocomment  types.wb.sidnlabs.nl. SOA $1
dig +short +nocomment  types.wb.sidnlabs.nl. SOA $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  a.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  a01.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  a02.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  aaaa.types.wb.sidnlabs.nl. AAAA $1
dig +short +nocomment  afsdb.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  afsdb01.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  afsdb02.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  caa.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  cds.types.wb.sidnlabs.nl. CDS $1
dig +short +nocomment  cert.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  cert01.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  cname.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  cname01.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  cname02.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  csync.types.wb.sidnlabs.nl. CSYNC $1
dig +short +nocomment  dhcid.types.wb.sidnlabs.nl. DHCID $1
dig +short +nocomment  dname.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname01.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname02.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  dname03.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  eui48.types.wb.sidnlabs.nl. EUI48 $1
dig +short +nocomment  eui64.types.wb.sidnlabs.nl. EUI64 $1
dig +short +nocomment  gpos.types.wb.sidnlabs.nl. GPOS $1
dig +short +nocomment  hinfo.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  hinfo01.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  hinfo02.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  isdn.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn01.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn02.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn03.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  isdn04.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  kx.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  kx01.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  kx02.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  l32.types.wb.sidnlabs.nl. L32 $1
dig +short +nocomment  l64.types.wb.sidnlabs.nl. L64 $1
dig +short +nocomment  loc.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  loc01.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  loc02.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  lp.types.wb.sidnlabs.nl. LP $1
dig +short +nocomment  mb.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  md.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  mf.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  mg.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  mg01.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  mg02.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  minfo.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  minfo01.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  mr.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mr01.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mr02.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  mx.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  mx01.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  naptr.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  naptr01.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  naptr02.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  nid.types.wb.sidnlabs.nl. NID $1
dig +short +nocomment  ninfo.types.wb.sidnlabs.nl. NINFO $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  ns.types.wb.sidnlabs.nl. NS $1
dig +short +nocomment  nsap.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  nsap01.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  ptr01.types.wb.sidnlabs.nl. PTR $1
dig +short +nocomment  px.types.wb.sidnlabs.nl. PX $1
dig +short +nocomment  rkey.types.wb.sidnlabs.nl. RKEY $1
dig +short +nocomment  rp.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rp01.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rp02.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  rt.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  rt01.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  rt02.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  spf.types.wb.sidnlabs.nl. SPF $1
dig +short +nocomment  srv.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  srv01.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  srv02.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  talink.types.wb.sidnlabs.nl. TALINK $1
dig +short +nocomment  tlsa.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  tlsa2.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  txt.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt01.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt02.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt03.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt04.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt05.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt06.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt07.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt08.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt09.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt10.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt11.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  txt12.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type1.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  type104.types.wb.sidnlabs.nl. NID $1
dig +short +nocomment  type105.types.wb.sidnlabs.nl. L32 $1
dig +short +nocomment  type106.types.wb.sidnlabs.nl. L64 $1
dig +short +nocomment  type107.types.wb.sidnlabs.nl. LP $1
dig +short +nocomment  type108.types.wb.sidnlabs.nl. EUI48 $1
dig +short +nocomment  type109.types.wb.sidnlabs.nl. EUI64 $1
dig +short +nocomment  type11.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  type12.types.wb.sidnlabs.nl. PTR $1
dig +short +nocomment  type13.types.wb.sidnlabs.nl. HINFO $1
dig +short +nocomment  type14.types.wb.sidnlabs.nl. MINFO $1
dig +short +nocomment  type15.types.wb.sidnlabs.nl. MX $1
dig +short +nocomment  type16.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type17.types.wb.sidnlabs.nl. RP $1
dig +short +nocomment  type18.types.wb.sidnlabs.nl. AFSDB $1
dig +short +nocomment  type19.types.wb.sidnlabs.nl. X25 $1
dig +short +nocomment  type20.types.wb.sidnlabs.nl. ISDN $1
dig +short +nocomment  type21.types.wb.sidnlabs.nl. RT $1
dig +short +nocomment  type22.types.wb.sidnlabs.nl. NSAP $1
dig +short +nocomment  type257.types.wb.sidnlabs.nl. CAA $1
dig +short +nocomment  type26.types.wb.sidnlabs.nl. PX $1
dig +short +nocomment  type27.types.wb.sidnlabs.nl. GPOS $1
dig +short +nocomment  type28.types.wb.sidnlabs.nl. AAAA $1
dig +short +nocomment  type29.types.wb.sidnlabs.nl. LOC $1
dig +short +nocomment  type3.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type33.types.wb.sidnlabs.nl. SRV $1
dig +short +nocomment  type35.types.wb.sidnlabs.nl. NAPTR $1
dig +short +nocomment  type36.types.wb.sidnlabs.nl. KX $1
dig +short +nocomment  type37.types.wb.sidnlabs.nl. CERT $1
dig +short +nocomment  type39.types.wb.sidnlabs.nl. DNAME $1
dig +short +nocomment  type4.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type49.types.wb.sidnlabs.nl. DHCID $1
dig +short +nocomment  type5.types.wb.sidnlabs.nl. CNAME $1
dig +short +nocomment  type52.types.wb.sidnlabs.nl. TLSA $1
dig +short +nocomment  type56.types.wb.sidnlabs.nl. NINFO $1
dig +short +nocomment  type57.types.wb.sidnlabs.nl. RKEY $1
dig +short +nocomment  type58.types.wb.sidnlabs.nl. TALINK $1
dig +short +nocomment  type59.types.wb.sidnlabs.nl. CDS $1
dig +short +nocomment  type7.types.wb.sidnlabs.nl. TXT $1
dig +short +nocomment  type8.types.wb.sidnlabs.nl. MG $1
dig +short +nocomment  type9.types.wb.sidnlabs.nl. MR $1
dig +short +nocomment  type99.types.wb.sidnlabs.nl. SPF $1
dig +short +nocomment  wks.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  wks01.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  wks02.types.wb.sidnlabs.nl. WKS $1
dig +short +nocomment  www.types.wb.sidnlabs.nl. A $1
dig +short +nocomment  x25.types.wb.sidnlabs.nl. X25 $1
dig +short +nocomment  types.wb.sidnlabs.nl. SOA $1
